// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXfDsIHKn0k9gC8CcuApiCxslRvN-tQ0k',
    appId: '1:1086458151397:web:4bb6ae13358bf0e6a12f0c',
    messagingSenderId: '1086458151397',
    projectId: 'anil-portfolio-388df',
    authDomain: 'anil-portfolio-388df.firebaseapp.com',
    storageBucket: 'anil-portfolio-388df.firebasestorage.app',
    measurementId: 'G-Y3EDJZKG2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSoksibKyGvm07mLYerxhW7hWoTvlnwDA',
    appId: '1:1086458151397:android:52594f945898b8faa12f0c',
    messagingSenderId: '1086458151397',
    projectId: 'anil-portfolio-388df',
    storageBucket: 'anil-portfolio-388df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEkO9UaXDr7MTvKQyZ-RNhgEKAXDy-TPM',
    appId: '1:1086458151397:ios:c1193702c85291e5a12f0c',
    messagingSenderId: '1086458151397',
    projectId: 'anil-portfolio-388df',
    storageBucket: 'anil-portfolio-388df.firebasestorage.app',
    iosBundleId: 'com.example.anilPortfolio',
  );
}
